**NumPy Basics**

NumPy stands for Numerical Python and also known as array oriented computing.

NumPy is a library written for scientific computing and data analysis.

NumPy consists of a powerful data structure called multidimensional arrays.

The most basic object in Numpy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).

**Why NumPy**

convenience & speed

NumPy is much faster than the standard python ways to do computations.

We don't have to do the explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

**Importing NumPy library**

In [ ]:
import numpy as np

**Creating array using .array() method**


In [ ]:
var=np.array([1,4,9,16,25,36])     
print(var)

[ 1  4  9 16 25 36]


In [ ]:
# to check the type of var
type(var)

numpy.ndarray

In [ ]:
# to get the dimension
var.shape

(6,)

In [ ]:
# to get the datatypes of array elements
var.dtype

dtype('int64')

**Indexing**

In [ ]:
a= np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(a)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
int64


In [ ]:
print(a[1,2])

6


In [ ]:
print(a[0,0])

1


In [ ]:
print(a[-1])

[6 7 8]


**Slicing**

In [ ]:
print(a[1:])

[[4 5 6]
 [6 7 8]]


In [ ]:
print(a[0::2])

[[1 2 3]
 [6 7 8]]


**Numpy will do elementwise calculations**


In [ ]:
# arange() is similar to range()
np_arr1 = np.arange(10)
np_arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_arr2 = np_arr1 + 2
np_arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**Performance Measurement**

%timeit is an python function, which can be used to check the time taken by a particular piece of code (A single execution statement, or a single method)



In [ ]:
#Time taken by the normal lists to do a task
%timeit [i**3 for i in range(10000)]

100 loops, best of 5: 2.94 ms per loop


In [ ]:
#Time taken by Numpy arrays to do the same task
%timeit np.arange(10000)**3

The slowest run took 19.18 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 32.2 µs per loop


**Creating numpy arrays**

In [ ]:
#np.zeros(shape)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#np.zeros_like(ndarray)
a = np.array([[2, 3], [2, 4], [8, 9]])
print(a)
print(a.shape)

[[2 3]
 [2 4]
 [8 9]]
(3, 2)


In [ ]:
np.zeros_like(a)
print(np.zeros_like(a))
print(a.shape)

[[0 0]
 [0 0]
 [0 0]]
(3, 2)


In [ ]:
#np.ones(shape)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.ones_like(ndarray)
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#np.full(shape,value)
np.full((3,2),2.5)


array([[2.5, 2.5],
       [2.5, 2.5],
       [2.5, 2.5]])

In [ ]:
#np.eye(m) : this method is used to create identity matrix , here m = n
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#np.diag(list) : is used to create diagonal matrix
np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**Copy and View**

In [ ]:
A=np.array(["Netzwerk", "Academy", "Banglore", "Maths", "BDS"])

myCopy=A.copy()
myview=A.view()

A[4]=("Python")

print(myCopy)
print(myview)

['Netzwerk' 'Academy' 'Banglore' 'Maths' 'BDS']
['Netzwerk' 'Academy' 'Banglore' 'Maths' 'Python']
