**Random numbers in numpy**

np.random.random()

generates a random number from 0 to 1

In [ ]:
import numpy as np

In [ ]:
print(np.random.random())

0.6290880984912425


In [ ]:
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.6519208764282111
0.858591103900052
0.5868027470643755


In [ ]:
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.1123682339992198
0.18239130207484522
0.6970481291717412



**np.random.seed()**

In [ ]:
np.random.seed()

In [ ]:
np.random.seed(10)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015
0.6336482349262754
0.7488038825386119


In [ ]:
np.random.seed(10)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.771320643266746
0.0207519493594015
0.6336482349262754
0.7488038825386119


In [ ]:
np.random.seed(300)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.45112256870005474
0.2210223417135454
0.3690812525293783
0.2907757037664177


In [ ]:
# you can specify the shape
x = np.random.random((4, 4))
x

array([[0.24107793, 0.78204643, 0.81109437, 0.40079054],
       [0.0259992 , 0.60937305, 0.6290881 , 0.65192088],
       [0.8585911 , 0.58680275, 0.70416835, 0.48590168],
       [0.68441634, 0.11236823, 0.1823913 , 0.69704813]])

**np.random.randint()**

In [ ]:
num = np.random.randint(low = 20, high =100)
num

64

In [ ]:
num = np.random.randint(low = 20, high =100,size = 5)
num

array([56, 80, 44, 48, 99])

In [ ]:
num = np.random.randint(low = 20, high =100,size = (5,5))
num

array([[33, 75, 43, 75, 63],
       [90, 77, 22, 30, 53],
       [33, 46, 57, 45, 25],
       [77, 20, 60, 45, 63],
       [53, 81, 62, 77, 21]])

**np.random.choice(list_of_choice,num_of_ele)**

In [ ]:
a = [24,27,22,47,35,82,-33,25,2.3,18]
a

[24, 27, 22, 47, 35, 82, -33, 25, 2.3, 18]

In [ ]:
np.random.choice(a,size = 3)


array([22., 24., 18.])

In [ ]:
np.random.choice(a,size = (5,5))


array([[ 47. ,  82. ,  24. ,   2.3,  22. ],
       [  2.3,  35. ,  35. ,  18. , -33. ],
       [  2.3,   2.3,  18. ,  47. , -33. ],
       [-33. ,  35. , -33. ,  47. ,  47. ],
       [  2.3,  82. ,  22. ,  22. ,  47. ]])

**Other Important Functions**

In [ ]:
x = np.random.random((4, 4))
x

array([[0.72796828, 0.3214473 , 0.86039918, 0.12032787],
       [0.54648103, 0.4960796 , 0.93685416, 0.06511093],
       [0.7374975 , 0.43061243, 0.84057618, 0.76492548],
       [0.27638725, 0.08058355, 0.64784155, 0.19585336]])


**np.round()**

rounds an array to given number of decimals

In [ ]:
# to round it to 3 decimal points
rounded = np.round(x, 3)
rounded

array([[0.728, 0.321, 0.86 , 0.12 ],
       [0.546, 0.496, 0.937, 0.065],
       [0.737, 0.431, 0.841, 0.765],
       [0.276, 0.081, 0.648, 0.196]])

In [ ]:
new = rounded * 100
new

array([[72.8, 32.1, 86. , 12. ],
       [54.6, 49.6, 93.7,  6.5],
       [73.7, 43.1, 84.1, 76.5],
       [27.6,  8.1, 64.8, 19.6]])


**astype()**

to change the data type of elements

In [ ]:

# to change the data type of elements to integers
intt = new.astype(int)
intt

array([[72, 32, 86, 12],
       [54, 49, 93,  6],
       [73, 43, 84, 76],
       [27,  8, 64, 19]])

In [ ]:
# to change the data type of elements to float
flt = intt.astype(float)
flt

array([[72., 32., 86., 12.],
       [54., 49., 93.,  6.],
       [73., 43., 84., 76.],
       [27.,  8., 64., 19.]])


**reshape()**

to reshape an array

In [ ]:
x = np.arange(32)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
x.shape

(32,)

In [ ]:
x = x.reshape(8,4)
x

In [ ]:
x.shape

(8, 4)

**Some other mathematical functions**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#np.sin()
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
#to get the exponential values i,e., e^num
np.exp(a)

In [ ]:
#creating and reshaping the array
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
#np.sum()  to get the sum of all the elements
np.sum(a)

In [ ]:
# along the column
np.sum(a,axis = 0)

In [ ]:
# along the row
np.sum(a,axis = 1)

**Transpose**

In [ ]:
a

In [ ]:
b=a.T
b

In [ ]:
# to get the maximum element
a = np.array([1,4,2,6,10,13,5,7,3])
a

In [ ]:
a.max()


In [ ]:
# to get the index at which the maximum element is present
a.argmax()